### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'C:\\Windows\\System32\\drivers\\etc\\hosts'

### ISSUE THREAD

**Issue by rescuedog2** [derekhe/msfs2020-google-map#119] opened 2021-11-26 08:29 UTC
BEFORE SUBMIT A BUG, PLEASE READ THE FAQ PAGE HERE: https://github.com/derekhe/msfs2020-google-map/wiki/FAQ

**Describe the bug**
Any help to get past this Errno 13 permissions error would be greatly appreciated.  

**To Reproduce**
Running run.bat as admin but when I click on Run, I get this error.  I tried changing permissions and owners to the best of my technical knowledge but can't get past this error.  Not sure what I am missing.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]  Win 10
 - MOD Version [e.g. 22]
 - MSFS Version = Steam

**Additional context**

**Comment by derekhe** [comment] 2021-11-26 09:17
Most of the case it is caused by your antivirus, please disable the hosts protection or add whitelist for this app.
https://github.com/derekhe/msfs2020-google-map/wiki/FAQ#host-related-issue

**Comment by rescuedog2** [comment] 2021-11-26 16:29
Thanks for the quick reply and help.  This was caused by Kaspersky.  For others that may need help, all I had to do was add an exclusion for this specific run.bat file.  Then be sure to checkbox the following:
Do not monitor application activity
Do not inherit restrictions from parent process
Do not monitor the activity of child apps

That's it.

**Comment by derekhe** [comment] 2021-11-27 08:21
Good, will close this one. Also added into FAQ page.

**Closed by derekhe** 2021-11-27 08:21 UTC
Labels: bug
